### ISSUE TITLE
email confirmation

### ISSUE THREAD

**Issue by mjhea0** [rpicard/explore-flask#77]
you should really encode the user id as well (with it's dangerous), and then confirm it, to make certain that specific confirm email is associated with the right email (in case multiple emails are registered). this is also a security issue. 

also, you reference a flask-mail method that you don't mentioned anything about - `send_mail`

**Comment by martinbel** [comment]
@rpicard Great book! Can you provide an example for `send_email`? Perhaps using Flask-Mail or whatever you think is most useful?

**Comment by jeffwidman** [comment]
After reading through this, I think it can be closed as a misunderstanding of how the design works by the OP.

**Comment by rpicard** [comment]
@jeffwidman Yeah, I think you're right.

As for the `send_email` stuff, there are a million ways to implement it. I personally like using an email service like Mailgun or Amazon SES because it feels easier. I'm going to close this out, but feel free to open a different issue if you have more questions. I'm not always prompt about answering, but I'll try to help. :)
